### ISSUE TITLE
Have you ever compared vgg architecture between tvm-cuda and tensorRT?

### ISSUE THREAD

**Issue by twmht** [AndrewZhaoLuo/TVM-Sandbox#2]
Hi,

This repo helps me a lot since TVM is really lack of document. I adopt some of the code here to do my experiment.

I tried to compare vgg-like architecture between TensorRT and tvm-cuda, the data type is cuda-fp16.

The layout is NCHW for both, and I found out TensorRT is faster than TVM a lot (10ms vs 19ms). I think the number of the trials is enough (`num_tasks * 800` as suggested in tvm.auto_scheduler)

So I am wondering if you ever compare TensorRT and TVM and found that TVM is slower?

Also I found this repo (https://github.com/vinx13/tvm-cuda-int8-benchmark) which compare TensorRT and TVM with int8, but from the result it seems that TVM should not be slower than TensorRT a lot.

Or can you me some suggestions to find out the reasons? I have used graph Debugger (https://tvm.apache.org/docs/arch/debugger.html)  to profiler each layer, but none of them can help me to find the root cause.

thank you.

**Comment by AndrewZhaoLuo** [comment]
Hey Ming, I've not personally tried VGG. There is a lot of magic settings you should probably set to get the best results from autoscheduler unfortunately. If you send me a script used for tuning I can take a look and make suggestions.

**Comment by twmht** [comment]
@AndrewZhaoLuo 

I use vgg since it's a plain structure and I thought it would be easily optimized by TVM, or any other backend.

And I also compare fp32 and fp16 and found out the running time is almost same.

the script is as the following

```python
def get_network(weight, batch_size):
    """Get the symbol definition and random weight of a network"""

    input_shape = (batch_size, 3, 320, 320)
    onnx_model = onnx.load(weight)
    input_name = "input"
    shape_dict = {input_name: input_shape}
    mod, params = relay.frontend.from_onnx(onnx_model, shape_dict)
    desired_layouts = {'nn.conv2d': ['NHWC', 'default'], 'image.resize2d': ['NHWC'], 'nn.upsampling': ['NHWC']}
    seq = tvm.transform.Sequential([relay.transform.RemoveUnusedFunctions(), relay.transform.ConvertLayout(desired_layouts)])
    with tvm.transform.PassContext(opt_level=3):
        mod = seq(mod)

    mod = tvm.IRModule.from_expr(mod["main"])
    mod = tvm.relay.transform.FastMath()(mod)
    mod = tvm.relay.transform.EliminateCommonSubexpr()(mod)
    BindPass = tvm.relay.transform.function_pass(lambda fn, new_mod, ctx: tvm.relay.build_module.bind_params_by_name(fn, params), opt_level=1)
    mod = BindPass(mod)
    mod = tvm.relay.transform.FoldConstant()(mod)
    mod = tvm.relay.transform.CombineParallelBatchMatmul()(mod)
    mod = tvm.relay.transform.FoldConstant()(mod)

    mod = tvm.relay.transform.InferType()(mod)
    mod = tvm.relay.transform.ToMixedPrecision()(mod)
    mod = tvm.relay.transform.EliminateCommonSubexpr()(mod)
    mod = tvm.relay.transform.FoldConstant()(mod)
    mod = tvm.relay.transform.CombineParallelBatchMatmul()(mod)
    mod = tvm.relay.transform.FoldConstant()(mod)

    return mod, params, input_shape

# RPC and cross compile
target = tvm.target.Target("cuda -arch=sm_53", host='llvm -mtriple=aarch64-linux-gnu')
mod, params, input_shape = get_network(
    weight,
    batch_size
)
tasks, task_weights = auto_scheduler.extract_tasks(mod["main"], params, target)


def run_tuning():
    print("Begin tuning...")
    #  measure_ctx = auto_scheduler.LocalRPCMeasureContext(repeat=1, min_repeat_ms=300, timeout=10)

    tuner = auto_scheduler.TaskScheduler(tasks, task_weights)
    tune_option = auto_scheduler.TuningOptions(
        num_measure_trials=20800,  # change this to 20000 to achieve the best performance
        builder = auto_scheduler.LocalBuilder(timeout=1000),
        #  runner=measure_ctx.runner,
        runner = auto_scheduler.RPCRunner('nano', '10.36.172.151', 9190, min_repeat_ms=300, timeout=1000, repeat=1),
        measure_callbacks=[auto_scheduler.RecordToFile(log_file)],
    )

    tuner.tune(tune_option)

run_tuning()
```

Does tensorcore matters? Although nano does not have tensorcore, in fp16 TensorRT still outperforms fp32 by 1.6x. 

Also, I tried to autotvm to see if any improvement,  I just changed auto_scheduler to autotvm from the above script, but autotvm is slower than auto_scheduler a lot by about 5x.

I am wondering how you debug if autotuning result is slow, can you share your experience?

**Comment by twmht** [comment]
Here are part of my nvprof result

![image](https://user-images.githubusercontent.com/1567200/163106663-d70ab69b-fc1a-4cc5-96ec-0ca4b821c769.png)

**Comment by AndrewZhaoLuo** [comment]
Hey, took a look. Yeah it seems the settings are the ones I would use. It seems we just underperform in FP16 realm.

Autoscheduler actually cannot support tensorcore at this time I believe, but if nano does not have it should not matter.  My main thing to look at would maybe be the HardwareParams under `python/tvm/auto_scheduler/search_task.py`. Right now it is set to autogenerate the correct parameters but perhaps since it is done over RPC it is not generating the right config which can affect search.

It also could just be we are outperformed right now than TensorRT for fp16. My 2c

**Comment by twmht** [comment]
> Right now it is set to autogenerate the correct parameters but perhaps since it is done over RPC it is not generating the right config which can affect search

I don't get it. Why RPC may not generate the right config?

From my experience, auto scheduler may outperform TensorRT7 in fp16, but slower than TensorRT8. Maybe TensorRT8 did much more optimization in fp16. But I am wondering how can we further improve fp16 conv in auto scheduler?

**Comment by AndrewZhaoLuo** [comment]
So if you don't pass in HardwareConfigs it will try to generate them from scratch: `src/auto_scheduler/search_task.cc`. It looks like it's acting kind of dumb so if you're host machine for example locally has a GPU it will grab info about that instead of your nano (but IDK, i don't know how this portion works very well). I am just worried about that so would double check.

Fp16 conv in autoscheduler yeah, i think most work in this realm is in metascheduler which makes it easier to extend various scheduling primitives and use them (https://discuss.tvm.apache.org/t/rfc-meta-schedule-autotensorir/10120). 

As for shorter term stuff, maybe you can extract individual conv workloads from your model and try them vs tensorrt more directly. It would let us know what workloads are slow vs tensorrt without trying to match profiling logs (but you can do that too).

**Comment by twmht** [comment]
@AndrewZhaoLuo 

After checking both hardware_params generated from both nano and my host machine, I found out they are all the same. For exmaple, here is the hardware_params from my host machine.

 
![image](https://user-images.githubusercontent.com/1567200/170191971-456a1165-e43b-4179-b625-2153e367ae5d.png)

the values are the same when using nano.

I am wondering if the default hardware_params is good enough ?

**Comment by AndrewZhaoLuo** [comment]
Hmm those actually seem appropriate for jetson nano, it could just be slower.
